const ADD_TASK = "ADD_TASK";
const DELETE_TASK = "DELETE_TASK";
const UPDATE_TASK = "UPDATE_TASK";
const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";
const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
const FETCH_TASKS_REQUEST = "FETCH_TASKS_REQUEST";
const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";
const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";
const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
const UPDATE_TASK_FAILURE = "UPDATE_TASK_FAILURE";
const UPDATE_STATUS = "UPDATE_STATUS";
const UPDATE_PRIORITY = "UPDATE_PRIORITY";
const UPDATE_OWNER = "UPDATE_OWNER";

export {
  ADD_TASK,
  DELETE_TASK,
  UPDATE_TASK,
  FETCH_TASKS_FAILURE,
  FETCH_TASKS_SUCCESS,
  FETCH_TASKS_REQUEST,
  DELETE_TASK_REQUEST,
  DELETE_TASK_SUCCESS,
  DELETE_TASK_FAILURE,
  ADD_TASK_REQUEST,
  ADD_TASK_SUCCESS,
  ADD_TASK_FAILURE,
  UPDATE_TASK_REQUEST,
  UPDATE_TASK_SUCCESS,
  UPDATE_TASK_FAILURE,
  UPDATE_STATUS,
  UPDATE_PRIORITY,
  UPDATE_OWNER,
};
